# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0

workflows:
  build-and-deploy:
    jobs:
      - run: npm run build
      - aws-s3/copy:
          from: dist/
          to: s3://polyglot-spa-navbar
          arguments: --recursive